<center>
 <div style="background-color:#FFDD57; padding:10px; border-radius:6px;">
 <h2><strong>PW 01: Data Preparation</strong></h2>
</div>    
</center>

#### 🎯 **Objective:** 
Understand the importance of **data preparation** — including **data cleaning, transformation, and organization** — to ensure data quality and reliability before analysis.

## <span style="color:blue"> **1-	Introduction to Data Science with Pandas**</span>

- **Objective:** Understand the basics of data science using Pandas by learning how to import, explore, and summarize datasets. Develop familiarity with core DataFrame operations such as selection, filtering, and basic statistics.

In [105]:
import pandas as pd

In [108]:
# load data
df = pd.read_csv ( 'cars.csv' )
#df = pd.read_json ( 'cars.json' )
#df = pd.read_excel ( 'cars.xlsx' )

In [107]:
type(df)

pandas.core.frame.DataFrame

- **DataFrame Overview**

In [111]:
df.head(7)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
5,5,Maruti Wagon R,Maruti,Wagon R,8,35000,Individual,Petrol,Manual,18.90,998,67.10,5,350000
6,6,Hyundai i10,Hyundai,i10,8,40000,Dealer,Petrol,Manual,20.36,1197,78.90,5,315000

In [113]:
df.tail(3)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [116]:
df.sample(3) # get 3 rows randomly

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
5392,6842,Hyundai i10,Hyundai,i10,11,90000,Dealer,Petrol,Manual,20.36,1197,78.90,5,275000
10427,13292,Maruti Vitara,Maruti,Vitara,4,75000,Dealer,Diesel,Manual,24.30,1248,88.50,5,775000
10546,13444,Skoda Superb,Skoda,Superb,7,84000,Dealer,Diesel,Automatic,17.20,1968,138.08,5,1040000

In [118]:
df.columns # get list of columns

['Unnamed: 0',
 'car_name',
 'brand',
 'model',
 'vehicle_age',
 'km_driven',
 'seller_type',
 'fuel_type',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'price']

In [121]:
df.dtypes # get data types of columns

Unnamed: 0             int64
car_name              object
brand                 object
model                 object
vehicle_age            int64
km_driven              int64
seller_type           object
fuel_type             object
transmission_type     object
mileage
                   float64
engine                 int64
max_power            float64
seats                  int64
price                  int64
dtype: object

In [122]:
df.info() # get summary of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #    Column             Non-Null Count Dtype
--- ------               -------------- -----
 0    Unnamed: 0         15411 non-null int64
 1    car_name           15411 non-null object
 2    brand              15411 non-null object
 3    model              15411 non-null object
 4    vehicle_age        15411 non-null int64
 5    km_driven          15411 non-null int64
 6    seller_type        15411 non-null object
 7    fuel_type          15411 non-null object
 8    transmission_type 15411 non-null object
 9    mileage            15411 non-null float64
 10 engine               15411 non-null int64
 11 max_power            15411 non-null float64
 12 seats                15411 non-null int64
 13 price                15411 non-null int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

- **Basic Statistics**

In [124]:
df.describe().round(2) # get numerical statistical sumary

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,price
count,15411.00,15411.00,15411.00,15411.00,15411.00,15411.00,15411.00,15411.00
mean,9811.86,6.04,55616.48,19.70,1486.06,100.59,5.33,774971.12
std,5643.42,3.01,51618.55,4.17,521.11,42.97,0.81,894128.36
min,0.00,0.00,100.00,4.00,793.00,38.40,0.00,40000.00
25%,4906.50,4.00,30000.00,17.00,1197.00,74.00,5.00,385000.00
50%,9872.00,6.00,50000.00,19.67,1248.00,88.50,5.00,556000.00
75%,14668.50,8.00,70000.00,22.70,1582.00,117.30,5.00,825000.00
max,19543.00,29.00,3800000.00,33.54,6592.00,626.00,9.00,39500000.00

In [125]:
df["brand"].value_counts() # frequency of values

brand
Maruti             4992
Hyundai            2982
Honda              1485
Mahindra           1011
Toyota              793
Ford                790
Volkswagen          620
Renault             536
BMW                 439
Tata
                 430
Mercedes-Benz      337
Skoda              334
Audi               192
Datsun             170
Jaguar              59
Land Rover          51
Jeep                41
Kia                 32
Porsche             21
Volvo               20
MG                  19
Mini                17
Nissan              11
Lexus               10
Isuzu                8
Bentley              3
Maserati             2
ISUZU                2
Ferrari              1
Mercedes-AMG         1
Rolls-Royce          1
Force                1
Name: count, dtype: int64

In [126]:
df["brand"].unique() # get list of possible values

array(['Maruti', 'Hyundai', 'Ford', 'Renault', 'Mini', 'Mercedes-Benz',
        'Toyota', 'Volkswagen', 'Honda', 'Mahindra', 'Datsun', 'Tata',
        'Kia', 'BMW', 'Audi', 'Land Rover', 'Jaguar', 'MG', 'Isuzu',
        'Porsche', 'Skoda', 'Volvo', 'Lexus', 'Jeep', 'Maserati',
        'Bentley', 'Nissan', 'ISUZU', 'Ferrari', 'Mercedes-AMG',
        'Rolls-Royce', 'Force'], dtype=object)

In [127]:
df["brand"].nunique() # get number of possible values

32

- **Column/Row Selection**

In [128]:
df["brand"]

0          Maruti
1         Hyundai
2         Hyundai
3          Maruti
4            Ford
           ...
15406     Hyundai
15407      Maruti
15408       Skoda
15409    Mahindra
15410       Honda
Name: brand, Length: 15411, dtype: object

In [131]:
df[["brand", "car_name"]] # multiple cols

           brand         car_name
0         Maruti      Maruti Alto
1        Hyundai    Hyundai Grand
2        Hyundai      Hyundai i20
3         Maruti      Maruti Alto
4           Ford    Ford Ecosport
...          ...               ...
15406    Hyundai      Hyundai i10
15407     Maruti    Maruti Ertiga
15408      Skoda      Skoda Rapid
15409 Mahindra Mahindra XUV500
15410      Honda       Honda City

[15411 rows x 2 columns]

In [132]:
df.iloc[0] # selects row by position

Unnamed: 0                       0
car_name              Maruti Alto
brand                       Maruti
model
                            Alto
vehicle_age                      9
km_driven                   120000
seller_type            Individual
fuel_type                   Petrol
transmission_type           Manual
mileage                       19.7
engine                         796
max_power                     46.3
seats                            5
price                       120000
Name: 0, dtype: object

In [134]:
df.iloc[3:5] # selects many rows by position

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [136]:
df2 = df.loc[df["price"] > 10000] # select rows by condition

In [140]:
df.loc[df["price"] > df["price"].mean(), "car_name"] # select rows by condition

8                Hyundai Venue
12                 Mini Cooper
15       Mercedes-Benz C-Class
22               Hyundai Creta
29             Toyota Fortuner
                 ...
15397            Toyota Innova
15404            Maruti Ertiga
15407            Maruti Ertiga
15409          Mahindra XUV500
15410                Honda City
Name: car_name, Length: 4365, dtype: object

In [141]:
print("the average of price of cars = ", df["price"].mean())

the average of price of cars = 774971.1164103562

- **Creating and Deleting Columns**

In [142]:
df["km_per_year"] = df["km_driven"] / df["vehicle_age"]

In [144]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price,km_per_year
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000,13333.333333
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000,4000.000000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000,5454.545455
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000,4111.111111
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000,5000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000,1191.444444
15407,19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000,9000.000000
15408,19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000,11166.666667
15409,19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000,760000.000000
15410,19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000,6500.000000

In [150]:
df.drop(["brand", "car_name"], axis=1) #remove many cols

,Unnamed: 0,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
0,0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...
15406,19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
15407,19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
15408,19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
15409,19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
15410,19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [149]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'price'],
      dtype='object')

- **Display the row with the minimum price**

In [152]:
df[df["price"] == df["price"].min()]

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
7607,9731,Maruti Wagon R,Maruti,Wagon R,21,80000,Individual,Petrol,Manual,18.9,998,67.1,5,40000

In [155]:
# sort data by price descending

df.sort_values(by="price", ascending=False, inplace=True)

In [156]:
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,price
3799,4845,Ferrari GTC4Lusso,Ferrari,GTC4Lusso,2,3800,Dealer,Petrol,Automatic,4.00,3855,601.0,4,39500000
10969,13944,Rolls-Royce Ghost,Rolls-Royce,Ghost,4,5000,Individual,Petrol,Automatic,10.20,6592,563.0,4,24200000
1172,1508,Bentley Continental,Bentley,Continental,9,9000,Dealer,Petrol,Automatic,9.50,5998,626.0,4,14500000
9722,12456,Mercedes-Benz S-Class,Mercedes-Benz,S-Class,3,4000,Dealer,Petrol,Automatic,7.81,4663,459.0,4,13000000
9364,12023,Porsche Cayenne,Porsche,Cayenne,4,24000,Dealer,Petrol,Automatic,12.50,3604,440.0,5,11100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7361,9413,Honda City,Honda,City,19,110000,Individual,Petrol,Manual,13.00,1493,100.0,5,50000
3787,4831,Maruti Alto,Maruti,Alto,19,120000,Individual,Petrol,Manual,18.90,1061,47.0,5,50000
12298,15593,Maruti Wagon R,Maruti,Wagon R,17,50000,Individual,Petrol,Manual,18.90,998,67.1,5,50000
13676,17349,Maruti Alto,Maruti,Alto,17,110000,Individual,Petrol,Manual,19.70,796,46.3,5,45000
7607,9731,Maruti Wagon R,Maruti,Wagon R,21,80000,Individual,Petrol,Manual,18.90,998,67.1,5,40000

## <span style="color:blue"> **1-	Introduction to Data Science with Pandas**</span>

- **Objective:** Understand the basics of data science using Pandas by learning how to import, explore, and summarize datasets. Develop familiarity with core DataFrame operations such as selection, filtering, and basic statistics.

In [1]:
import pandas as pd

df = pd.read_excel("sales_data.xlsx")

print(df.head())
print(df.info())
print(df.isnull().sum())

     country order_value_EUR          cost                  date     category \
0     Sweden          98320.37   77722.25              8/23/2020        Games
1     France          46296.26   40319.41              5/15/2020        Games
2 Portugal          140337.34 115708.14 2020-04-09 00:00:00        Appliances
3     France        203604.46 175344.16                6/26/2019 Electronics
4      Italy        127075.41 110924.13                9/24/2019     Clothing

       customer_name     sales_manager              sales_rep device_type \
0     Konopelski LLC      Maxie Marrow     Tarrah Castelletti      Tablet
1         Wisoky Inc     Othello Bowes Amelina Piscopiello         Tablet
2      Hegmann Group Celine Tumasian            Corene Shirer          PC
3    Kirlin and Sons     Othello Bowes           Crysta Halls      Mobile
4 Labadie and Sons      Piggy Roscrigg         Joshua Prevost          PC

      order_id
0 70-0511466
1 77-3489084
2 65-8218141
3 29-5478106
4 57-6602854
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #    Column            Non-Null Count Dtype
--- ------              -------------- -----
 0    country           1000 non-null    object
 1
 order_value_EUR 995 non-null    float64
 2   cost             999 non-null   float64
 3   date             1000 non-null  object
 4   category         1000 non-null  object
 5   customer_name    1000 non-null  object
 6   sales_manager    1000 non-null  object
 7   sales_rep        1000 non-null  object
 8   device_type      995 non-null   object
 9   order_id         1000 non-null  object
dtypes: float64(2), object(8)
memory usage: 78.3+ KB
None
country            0
order_value_EUR    5
cost               1
date               0
category           0
customer_name      0
sales_manager      0
sales_rep          0
device_type        5
order_id           0
dtype: int64